# pip is being used for most of installation
# it has been more stable for some unknown reason (geopandas)
name: knoxvilleopendata
channels:
  - conda-forge
dependencies:
  - python=3.7
  - ipyleaflet
  - jupyterlab
  - pypdf2
  - numpy
  - pandas
  - xlrd
  - nodejs
  - matplotlib
  - pip:
    - requests
    - requests-html
    - requests-cache
    - geopandas
    - camelot-py
    - opencv-python
